### ISSUE TITLE
Media duration slider doesn't move with the media playback

### ISSUE THREAD

**Issue by dmiles4824** [Kmr117/utility-media-player#11]
It seems that it will be really difficult, if not impossible, to handle playback and seeking with the same slider. If we handle seeking by using event listeners on the slider, and the media automatically moves the slider as it plays, it will just constantly fire, right?

Maybe use two seperate bars, one for seeking and one to display the current time?

**Comment by ghost** [comment]
Now resolved with a better implementation of the listener.
